// fifo_cdc.v

// Generated using ACDS version 23.3 104

`timescale 1 ps / 1 ps
module fifo_cdc (
		input  wire [7:0] data,    //  fifo_input.datain
		input  wire       wrreq,   //            .wrreq
		input  wire       rdreq,   //            .rdreq
		input  wire       wrclk,   //            .wrclk
		input  wire       rdclk,   //            .rdclk
		output wire [7:0] q,       // fifo_output.dataout
		output wire       rdempty, //            .rdempty
		output wire       wrfull   //            .wrfull
	);

	fifo_cdc_fifo_1923_wtv3t7a fifo_0 (
		.data    (data),    //   input,  width = 8,  fifo_input.datain
		.wrreq   (wrreq),   //   input,  width = 1,            .wrreq
		.rdreq   (rdreq),   //   input,  width = 1,            .rdreq
		.wrclk   (wrclk),   //   input,  width = 1,            .wrclk
		.rdclk   (rdclk),   //   input,  width = 1,            .rdclk
		.q       (q),       //  output,  width = 8, fifo_output.dataout
		.rdempty (rdempty), //  output,  width = 1,            .rdempty
		.wrfull  (wrfull)   //  output,  width = 1,            .wrfull
	);

endmodule
